language: java

before_install:
    - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
    - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
    
install:
    mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
    
script:
    mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
  
deploy:
  provider: releases
  api_key:
    secure: GITHUB_DEPLOYMENT_KEY
  branch: master
  skip_cleanup: true
  on:
    repo: zapr-oss/druidry
    branch: master
